version: "3"

services:
  frontend:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./bar-patron-app/build:/usr/share/nginx/html
    environment:
      SERVER_URL: "http://backend:8005/api"

  backend:
    build: ./bar-patron-server/
    ports: 
     - "8005:8005"
    environment:
      DATABASE_URL: "mongodb://db:27017/test"
    deploy:
      restart_policy:
        condition: any

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - pg_data:/data/db
    deploy:
      restart_policy:
        condition: any

volumes:
  pg_data:
